name: TestDriver.ai

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          version: "5.1.0"
          key: ${{secrets.TESTDRIVER_API_KEY}}
          prompt: |
            1. /run testdriver/testdriver.yaml
          prerun: |
            cd $env:TEMP
            npm init -y
            npm install
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
